import datetime
import os 
import json

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
FILE_NAME = os.path.join(BASE_DIR,"messages.json")
file_name = "messages.txt"
HEADER =("\n\n" + "<=: All of the messages := >".center(80) + "\n" + ("\t"*6 + "="*48) + "\n\n")



def load_json_safely(file_path):
    """
    Safely loads JSON data from a file.
    """
    
    try:
        with open(file_path,"r") as jf:
            return json.load(jf)
    except(FileNotFoundError, json.JSONDecodeError):
        return {}



def load_text_safely(file_path):
    """
    Safely loads text data from a file.
    """
    
    try:
        with open(file_path,"r") as tf:
            return tf.read()
    except FileNotFoundError:
        return ""



def files_have_data(json_data, text_data):
    """
    Checks if both JSON and text data have content.

    Returns:
        bool: True if both have data, False otherwise.
    """
    
    return bool(json_data) and bool(text_data.strip())



def ask_user_reset_decision():
    """
    Asks user whether to reset files.
    Returns True for reset, False for keep.
    """
    while True:
        ans = input("Do you want to start fresh? [y/n]: ").lower()
        if ans == 'y':
            return True
        if ans == 'n':
            return False
        print("Invalid input. Enter 'y' or 'n'.")
        
        

def initialize_files(json_path, text_path, header):
    """
    Clears JSON file and writes header to text file.
    """
    with open(json_path, "w") as jf:
        json.dump({}, jf)

    with open(text_path, "w") as tf:
        tf.write(header)
    
    
def reset_file():
    json_data = load_json_safely(FILE_NAME)
    text_data = load_text_safely(file_name)

    if files_have_data(json_data, text_data):
        reset = ask_user_reset_decision()
        if reset:
            initialize_files(FILE_NAME, file_name, HEADER)
    else:
        initialize_files(FILE_NAME, file_name, HEADER)
        
        
class Message:   
    """
    Represents a single chat message.

    Attributes:
        msg (str): Message content.
        time (str): Formatted timestamp.
        owner (str): Name of the sender.
    """
    
    def __init__(self,msg,time,owner):
        self.msg = msg
        self.time = time.strftime("\t\t%Y-%m-%d ==> [ %H:%M:%S ]")
        self.owner = owner
    
    def msg_show(self):
        try:
            with open(FILE_NAME, "r") as file:
                data = json.load(file)
        except (FileNotFoundError, json.JSONDecodeError):
            data = {}
            
        # new msg_id is generated by finding the maximum existing msg_id in the data and adding 1 to it, ensuring that each message has a unique identifier.
        msg_id = max(map(int, data.keys()), default=0) + 1
        
        data[str(msg_id)] = {
            "owner": self.owner,
            "time": self.time,
            "msg": self.msg
        }
        with open(FILE_NAME,"w") as file:
            json.dump(data,file,indent=4)


        with open(file_name,"a")as f:
            f.write(f"{self.owner} : {self.msg} \n\n{self.time} \n" + "-"*50 + "\n\n")
            
            
            
            
